### ISSUE TITLE
Leaving Blank Fields in Edit/New Task Window Throws Exceptions

### ISSUE THREAD

**Issue by Daniel-Wallace** [mczechmczech/Senior-Project-Fall-2017#52]

**Comment by Daniel-Wallace** [comment]
Leaving the date field blank throws exception.
Leaving the project number field blank throws exception.
Determine how to fix exceptions or prevent user from creating a task without those values

**Comment by jordannstrong** [comment]
https://github.com/mczechmczech/Senior-Project-Fall-2017/commit/1a73e3ea2979b6c5be923eab5f8d363157648c6b

Does a check to see if the date and project number fields are empty. If they are, does not create the task and alerts the user that they cannot be empty.
